note_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include("notebook.urls")),
]

notebook/urls.py
from django.urls import path
from . import views 

app_name = "notebook"
urlpatterns = [
    path('', views.notes , name = "notes"),
]

notebook/models.py
from django.db import models

class Note(models.Model):
    title = models.CharField(max_length=40)
    content = models.CharField(max_length=300)
    


    def __str__(self):
        return f"{self.title}  {self.content} "

notebook/views.py
from django.shortcuts import render
import datetime
from .models import Note


#def register(request):

#def login(request):

def notes(request):
    if request.method == "POST":
        content = request.POST.get('content')
        title = request.POST.get('title')
        Note.objects.create(title=title, content=content)
    return render(request, "notebook/notes.html", {
        "notes": Note.objects.all()
    })

# def delete(request):
    # if request.method=="POST":
        # title = Note.object.get('title')
    # Note.objects.filter(title=title).delete()
    # return render(request, "notebook/notes.html", {
        # "notes": Note.objects.all()
# })

notebook/templates/notebook/layout.html
{% load static %}
<head>
    <title> Layout </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/style.css'%}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
</head>
<body class="container-fluid" style="background-color: #DFDDD8; font-family: Verdana, Geneva, Tahoma;">
    <div class="row" style="background-color: #72B9BC;">
    <div class="navbar" style="background-color: #72B9BC; justify-content: left;">
        <a class="navbar-brand" style="font-size: 30; font-weight: bolder;"> Notes </a>
        <div class="form-inline">
            <a class="btn rounded" id="add_btn">Add</a>
        </div>
    </div>
    <a class="fas fa-bars fa-2x" style="position: absolute; right: 5; margin-top: 10px;"></a>

    </div>
    <div class="container-fluid" style="padding: 10px;">
        <div class="row mx-auto ">
            {% block body %}

            {% endblock %}
        </div>
        <a class="btn rounded-pill" id="top_btn" style="box-shadow: 6px 6px 29px -6px rgba(0,0,0,.80); position: fixed; left:-1%; bottom: 10%; background-color: #72B9BC;">
            Back to Top
        </a>
        <div class="popup">
            <div class="card content">
                <div class="card-body">
                <h4 class="card-title" style="font-weight: bold;"> Post A New Note </h4>
                <form action="{% url 'notebook:notes' %}" method="post">
                    {% csrf_token %}
                   <div class="input"> Note  Title </div>
                   <div><input name="title" style="margin-top: -10px;"></div>
                    <div class="input">Note Content </div>
                    <div><input class="note_txt" name="content"></div>
                    <div class="row">
                        
                        <input class="btn" type="submit" style="margin-top: 20px;"> 
                        <a class="btn rounded" id="close_btn" style="position:absolute; font-weight: bold; margin-top: 20px; right: 0;">X</a>
                        
                    </div>
                </form>
                </div>
            </div>
        </div>
    </div>
</body>
<script type="text/javascript" src="{% static 'js/notes_js.js' %}"></script>

notebook/templates/notebook/login.html
{% extends "notebook/layout.html" %}
<head>
    <title> Log In </title>
</head>
<body>
    {% block body %}

    <div class="login" style="height: 70%; width:50%; justify-content: center; background-color: #DFDDD8; display: flex;">
    
        <form style="display: flex;">
            <div class="row"><input name="username" placeholder="username"></div>
            <div class="row"><input name="password" placeholder="password"></div>
            <div class="row"><input class="btn" name="submit" type="submit"></div>
        </form>
    

    </div>

    {% endblock %}
</body>

notebook/templates/notebook/notes.html
{% extends "notebook/layout.html" %}
<head>
    <title> Note Page </title>
</head>
<body>
    {% block body %}
        {% for note in notes %}
            <div class="col-sm-12 col-md-12 col-lg-2 mx-auto my-1 rounded note" style="min-height: 200px; min-width: 400px; background-color: #F2DCAC; border: 1px solid gray;">
                <div class="row" style="justify-content: center; font-size: 20; font-weight: light;">{{ note.title }}</div>
                <div class="col-12">{{ note.content }}</div>
                <div class="row" style="position: absolute; bottom:3;">
                    
                </div>
                <i class="far fa-trash-alt fa-2x del"></i>
            </div>
        {% endfor %}
    {% endblock %}
</body>

notebook/templates/notebook/register.html
{% extends "notebook/layout.html" %}
<head>
    <title> Register </title>
</head>
<body>
    {% block body %}
    <div class="Register" style="height: 70%; width:50%; justify-content: center; background-color: #DFDDD8; display: flex;">
    
        <form style="display: flex;">
            <div class="row">First Name <input name="first_name" placeholder="First Name"></div>
            <div class="row">Last Name <input name="last_name" placeholder="Last Name"></div>
            <div class="row">Username <input name="username" placeholder="Username"></div>
            <div class="row">Password <input name="password" placeholder="Password"></div>
            <div class="row">Confirm Password <input name="confirm password" placeholder="Re-enter password"></div>
            <div class="row">Email <input name="email" placeholder="Email"></div>
            <div class="row"><input class="btn" name="submit" type="submit"></div>
        </form>
    
    </div>
    {% endblock %}
</body>